### PR TITLE
Add strategy for blast6 data

### PR DESCRIPTION
**Pull request by vaastav**
Apparently not many people use this as input and only as output format.

### CODE REVIEW

**Comment by vaastav** [comment]
Addresses Issue #47

**Comment by mbhall88** [comment]
@vaastav are you working on adding tests to this now? I feel uncomfortable with this being merged and dropping test coverage by so much.

**Comment by vaastav** [comment]
@mbhall88  Yes, I am. It's just not prioritised for now as not many people use this format as an input format.

**Comment by mbhall88** [comment]
My only concern is that if they don't get added now, we won't get around to doing them later.

**Comment by Benjamin-Lee** [comment]
I'm woking on removing the BLAST+6 format and showing an example of how you can use hypothesis-csv to generate it instead

**Comment by Benjamin-Lee** [comment]
See #72

**Comment by vaastav** [comment]
@Benjamin-Lee I thought we agreed on letting the individual attribute generators be a part of the repo and then showing how to use those with hypothesis-csv. This would mean only removing the blast6 function. Plus, the low coverage is really from a function in the utilities file that is not tested.

**Pull request merged**
