### PR TITLE
Used fastq strategy for multi-FASTA

### PR DESCRIPTION
**Pull request by scatcher125**

### CODE REVIEW

**Comment by mbhall88** [comment]
You need to handle the case where `wrap_length = 0`

**Comment by scatcher125** [comment]
> You need to handle the case where `wrap_length = 0` i.e no wrapping

I'm actually a bit confused about why wrap_length=0 is ok for FASTQ but not FASTA. Also about whether I would handle this in the tests or in the code itself.

**Comment by mbhall88** [comment]
> > You need to handle the case where `wrap_length = 0` i.e no wrapping
> 
> I'm actually a bit confused about why wrap_length=0 is ok for FASTQ but not FASTA. Also about whether I would handle this in the tests or in the code itself.

So I think there is a slight difference between fastq and fasta implementations in that fasta is `None` by default and fastq is `80` by default. I basically say in fastq that if the `wrap_length` is `0`, dont wrap, otherwise wrap.

**Comment by scatcher125** [comment]
> > > You need to handle the case where `wrap_length = 0` i.e no wrapping
> > 
> > 
> > I'm actually a bit confused about why wrap_length=0 is ok for FASTQ but not FASTA. Also about whether I would handle this in the tests or in the code itself.
> 
> So I think there is a slight difference between fastq and fasta implementations in that fasta is `None` by default and fastq is `80` by default. I basically say in fastq that if the `wrap_length` is `0`, dont wrap, otherwise wrap.

Oh I see. Perhaps I could edit fasta_entry to use the same strategy.

**Pull request merged**
